<a href="https://colab.research.google.com/github/Ashton94089/Actuarial-Practice/blob/main/03_python_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python for Actuaries Part 3

Agenda

In this notebook, we will cover:

* Introducing Pandas
* Series and DataFrames
* Data Access and Inspection
* Manipulating and Cleaning Data
* Reading Files

Introduction to Pandas

Pandas is one of the most popular libraries for data analysis and manipulation in Python. It was specifically designed to work efficiently and easily with structured data, similar to spreadsheet applications like Excel.

Pandas offers two main structures for handling data:

* Series: A one-dimensional data structure, similar to a list or an array.

* DataFrame: A two-dimensional data structure, comparable to a table in a database or an Excel spreadsheet.

Why Pandas?

Pandas is especially useful when it comes to ingesting, processing, and analyzing large amounts of data. Typical tasks that Pandas simplifies include:

* Ingesting data from various formats (e.g., CSV, Excel, SQL databases).
* Efficiently inspecting and analyzing data.

* Data cleansing and manipulation (e.g., handling missing values, renaming columns).

* Transforming and aggregating data for further analysis or visualization.

Thanks to its broad functionality and ease of use, Pandas has become a standard tool for data analysis, particularly in data science, financial analysis, and insurance.

Below, we will look at the key features of Pandas and learn how to efficiently ingest, analyze, and clean data.

Criticisms of Pandas

Although Pandas is a powerful library, there are some criticisms to keep in mind:

1. Memory and computational overhead: Pandas is memory-intensive because it loads data into RAM. With very large datasets, this can lead to performance issues. For large datasets that don't fit in RAM, alternative tools like Dask, PySpark, or Apache Arrow, which are optimized for distributed processing, should be considered.

2. Complexity with large data pipelines: Pandas is very efficient for smaller projects and analyses. However, with larger data pipelines or complex data analyses, the code can become unwieldy and difficult to maintain. In particular, dealing with many nested Pandas functions can make the code difficult to understand.

Despite these limitations, Pandas remains a powerful tool for most data analyses, especially with medium-sized datasets.

In [ ]:
# To be able to work with Pandas, it must of course be imported.
import pandas as pd
# Typically, numpy is also required.
import numpy as np

Series

A Pandas Series is a one-dimensional data structure similar to a list or array. It consists of a series of values, each assigned an index. Pandas Series can contain various data types, such as integers, floating-point numbers, or strings.

Properties of a Series:

* Index: Every series has an associated index, which by default starts at 0 but can also be explicitly set (e.g., for dates).

* Homogeneous Data: All elements of a series have the same data type (like arrays).

Series are useful when working with one-dimensional data, such as a list of claims amounts in an insurance portfolio.

Example 1: Claims history over several years

In this example, we store the annual claims history of an insurance company as a Pandas Series.

In [ ]:
# Damage history over five years
years = ['2018', '2019', '2020', '2021', '2022']
damage_progression = pd.Series([10000, 15000, 13000, 12000, 11000], index=years)
print(damage_progression)

2018    10000
2019    15000
2020    13000
2021    12000
2022    11000
dtype: int64

Another example is (synthetic) stock price charts:

In [ ]:
# Parameters for the simulation
# 固定隨機亂數種子，確保每次執行產生的隨機數都一樣（方便重複實驗）
np.random.seed(42)
# 生成從 2023-01-01 開始，連續 365 天的時間序列 index
days = pd.date_range(start='2023-01-01', periods=365, freq='D')
# 股票初始價格 $S_0 = 100$
starting_price = 100 # Starting price of the stock
# 波動率（標準差 $\sigma$）= 2%
volatility = 0.02 # Stock volatility (2%)
# 期望日報酬率（平均值 $\mu$）= 0.1%
returns = 0.001 # Expected daily return (0.1%)

# Generate daily changes based on Brownian motion
# 1. 根據常態分配生成每天的對數報酬率變化量
changes = np.random.normal(loc=returns, scale=volatility, size=len(days))

# Calculate the stock prices using the cumulative sum
# 2. 利用對數報酬率的「累加（cumsum）」與「指數（exp）」計算每天的股價
prices = starting_price * np.exp(np.cumsum(changes))

# Create the Pandas Series
# 3. 將計算好的價格陣列包裝成 Pandas Series，並以日期作為 index
stock_price = pd.Series(prices, index=days)

# Output of the first few days of the stock price chart
# 4. 印出前 20 天的股價結果
print(stock_price.head(20))

2023-01-01    101.099428
2023-01-02    100.921116
2023-01-03    102.339217
2023-01-04    105.610051
2023-01-05    105.221798
2023-01-06    104.835006
2023-01-07    108.307240
2023-01-08    110.092475
2023-01-09    109.172719
2023-01-10    110.474244
2023-01-11    109.564570
2023-01-12    108.657362
2023-01-13    109.293695
2023-01-14    105.295754
2023-01-15    101.826944
2023-01-16    100.788977
2023-01-17     98.866689
2023-01-18     99.589558
2023-01-19     97.895133
2023-01-20     95.263883
Freq: D, dtype: float64

DataFrames

A DataFrame is the core component of Pandas and represents a two-dimensional, table-like data structure containing columns and rows. A DataFrame can be viewed as a collection of Pandas Series that share a common structure. Each column is assigned a unique name, and each row can be referenced by an index.

Characteristics of a DataFrame:

* Rows and columns: A DataFrame consists of rows and columns, where each column can have its own data type (e.g., a column with numerical values ​​and a column with strings).
* Flexible indexing: Rows and columns can be accessed via the index or column names.
* Data sources: DataFrames can be created from various data sources, such as CSV files, Excel files, SQL databases, or even Python dictionaries and lists.

Example 1: Creating a DataFrame for insurance data

In this example, we create a DataFrame containing some basic information about insurance policies, such as the policy ID, the policyholder, the premium amount, and the number of claims.

In [ ]:
# Creating a DataFrame
# Define the data

data = {
    'Police_ID':pd.Series([101, 102, 103, 104, 105, 106, 107, 108, 109, 110],dtype='int64'),
    'Insured_person':pd.Series(['Max Müller', 'Anna Schmitz', 'Tom Meier', 'Laura Klein', 'Peter Schneider',
                  'Julia Weber', 'Stefan Jung', 'Monika Richter', 'Clara Hofmann', 'David Krause'],dtype='string'),
    'Age':pd.Series([18, 47, 49, 14, 15, 31,  1, 54,  3, 16],dtype='int64'),
    'Premium_Amount':pd.Series([500, 600, 550, 620, 480, 700, 520, 610, 580, 540], dtype='float64'),
    'Claims':pd.Series([2, 1, 0, 3, 2, 1, 1, 0, 4, 2],dtype='int64'),
    'Policy_Start_Date':pd.to_datetime(['2019-01-15', '2020-05-20', '2021-03-10', '2018-11-22',
                      '2019-07-01', '2020-02-17', '2021-09-09', '2022-01-01',
                      '2019-12-25', '2020-06-14'])
}

# Creating the DataFrame
insurance_df = pd.DataFrame(data)

# Outputting the DataFrame
insurance_df

   Police_ID   Insured_person  Age  Premium_Amount  Claims Policy_Start_Date
0        101       Max Müller   18           500.0       2        2019-01-15
1        102     Anna Schmitz   47           600.0       1        2020-05-20
2        103        Tom Meier   49           550.0       0        2021-03-10
3        104      Laura Klein   14           620.0       3        2018-11-22
4        105  Peter Schneider   15           480.0       2        2019-07-01
5        106      Julia Weber   31           700.0       1        2020-02-17
6        107      Stefan Jung    1           520.0       1        2021-09-09
7        108   Monika Richter   54           610.0       0        2022-01-01
8        109    Clara Hofmann    3           580.0       4        2019-12-25
9        110     David Krause   16           540.0       2        2020-06-14

Note that the DataFrame does not have an explicit index. That is why there is a column ranging from 0 to 9 at the beginning.

In [ ]:
insurance_df.dtypes

Police_ID                     int64
Insured_person       string[python]
Age                           int64
Premium_Amount              float64
Claims                        int64
Policy_Start_Date    datetime64[ns]
dtype: object

Here is another example of time-dependent (synthetic) data:

In [ ]:
import numpy as np
import pandas as pd

# Parameters for the simulation
np.random.seed(42)
days = pd.date_range(start='2023-01-01', periods=365, freq='D')

# Stock parameters for different companies
companies = {
    'Apple':{'start_price':150,'volatility':0.02,'return':0.001},
    'Nvidia':{'start_price':200,'volatility':0.025,'return':0.0012},
    'Google':{'start_price':180,'volatility':0.018,'return':0.0008},
    'SAP':{'start_price':120,'volatility':0.015,'return':0.0009},
    'Microsoft':{'start_price':250,'volatility':0.02,'return':0.0011},
    'Tesla':{'start_price':200,'volatility':0.03,'return':0.0015},
}

# Create a DataFrame to store all stock price histories
stock_histories = pd.DataFrame(index=days)

# Simulation of stock prices for each company
for company, parameters in companies.items():
  start_price = parameters['start_price']
  volatility = parameters['volatility']
  daily_return = parameters['return']

  # Generate daily changes based on Brownian motion
  changes = np.random.normal(loc=daily_return, scale=volatility, size=len(days))

  # Calculate stock prices using cumulative sum
  prices = start_price * np.exp(np.cumsum(changes))

  # Add the simulation as a series into the DataFrame
  stock_histories[company] = prices

# Output the first 20 days of simulated stock price histories
stock_histories.head(20)

,Apple,Nvidia,Google,SAP,Microsoft,Tesla
2023-01-01,151.649142,198.241673,180.780225,119.962716,249.583068,202.973532
2023-01-02,151.381674,199.594771,177.766583,120.212441,243.814047,196.736174
2023-01-03,153.508826,199.897348,179.221040,116.767819,243.064142,205.550467
2023-01-04,158.415077,200.626682,173.950956,118.490457,239.227495,205.251066
2023-01-05,157.832697,197.023032,177.345215,119.215139,236.726269,205.675448
2023-01-06,157.252509,197.380510,179.003428,121.122194,239.793002,210.407444
2023-01-07,162.460860,200.093218,179.974197,116.077268,248.209748,212.202784
2023-01-08,165.138713,207.734732,183.332589,119.878856,250.452074,218.685898
2023-01-09,163.759079,213.032281,189.063033,119.735824,244.802048,220.908849
2023-01-10,165.711366,225.083911,192.700878,121.852414,247.260385,217.212698
2023-01-11,164.346855,221.072252,186.569420,120.074454,253.528084,219.910832
2023-01-12,162.986042,226.217651,182.467305,121.292334,250.730572,212.812260
2023-01-13,163.940542,227.529783,180.571040,119.498328,250.334644,213.826975
2023-01-14,157.943632,240.621755,180.800446,118.492047,250.683795,213.934578
2023-01-15,152.740416,236.091339,182.639045,122.053115,247.050902,212.922182
2023-01-16,151.183465,231.464315,180.412949,121.814096,250.550377,212.421101
2023-01-17,148.300034,228.295513,181.165357,122.322081,250.220128,201.062370
2023-01-18,149.384337,216.749760,178.861774,124.040557,252.606184,198.076518
2023-01-19,146.842700,214.176326,177.045361,125.078785,248.435151,198.927166
2023-01-20,142.895825,210.402279,172.757016,125.474193,246.542078,200.183501

We now have two nice sample datasets: `insurance_df` and `stock_histories`. Let's see what we can do with them.

Standard Pandas Functions

Pandas offers a range of helpful standard functions for inspecting data quickly and efficiently. Here are some of the most important ones: `head()` and `tail()`

You can use `head()` and `tail()` to display the first or last entries of a DataFrame or Series. This is useful for gaining a quick overview of the data structure. We have already seen examples of `head()` above.

The functions `describe()` and `info()` are more useful for getting an initial impression of a dataset.

In [ ]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Police_ID          10 non-null     int64
 1   Insured_person     10 non-null     string
 2   Age                10 non-null     int64
 3   Premium_Amount     10 non-null     float64
 4   Claims             10 non-null     int64
 5   Policy_Start_Date  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), string(1)
memory usage: 612.0 bytes

In [ ]:
stock_histories.describe()

            Apple      Nvidia      Google         SAP   Microsoft       Tesla
count  365.000000  365.000000  365.000000  365.000000  365.000000  365.000000
mean   167.850773  224.848564  334.409550  171.437584  392.180590  285.122855
std     32.734342   23.094083  119.476135   27.567769  111.641143   42.962466
min    124.387660  178.295112  163.329860  116.077268  236.726269  194.397337
25%    138.046904  210.402279  219.369854  153.248588  301.510627  244.690657
50%    159.990521  227.307357  359.991431  168.130991  340.281680  297.725328
75%    189.656332  238.265856  419.665054  184.807960  498.434008  315.574291
max    239.182908  291.560517  554.977232  260.720802  636.691147  382.720169

Other important information includes, for example, columns, index, or shape. (Note: these are attributes of the DataFrame, not functions.)

In [ ]:
stock_histories.columns

Index(['Apple', 'Nvidia', 'Google', 'SAP', 'Microsoft', 'Tesla'], dtype='object')

In [ ]:
insurance_df.shape

(10, 6)

In [ ]:
stock_histories.index

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-12-22', '2023-12-23', '2023-12-24', '2023-12-25',
               '2023-12-26', '2023-12-27', '2023-12-28', '2023-12-29',
               '2023-12-30', '2023-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

Data Access in Pandas

Pandas offers various methods for accessing data in a DataFrame. These include accessing columns, rows, or specific elements using `loc` and `iloc`.

Accessing Columns

A DataFrame column can be easily accessed using the column name. There are two ways to do this:

1. Access using dot notation

In [ ]:
insurance_df.Insured_person

0         Max Müller
1       Anna Schmitz
2          Tom Meier
3        Laura Klein
4    Peter Schneider
5        Julia Weber
6        Stefan Jung
7     Monika Richter
8      Clara Hofmann
9       David Krause
Name: Insured_person, dtype: string

2. With column names in square brackets (more common)

In [ ]:
insurance_df['Insured_person']

0         Max Müller
1       Anna Schmitz
2          Tom Meier
3        Laura Klein
4    Peter Schneider
5        Julia Weber
6        Stefan Jung
7     Monika Richter
8      Clara Hofmann
9       David Krause
Name: Insured_person, dtype: string

Accessing rows

`loc[]` – Access by label (index-based)

`loc[]` allows you to access rows and columns based on their labels. This method uses explicit index names or column names.

In [ ]:
stock_histories.loc['01-01-2023'] #Note: Date format is actually incorrect

Apple        151.649142
Nvidia       198.241673
Google       180.780225
SAP          119.962716
Microsoft    249.583068
Tesla        202.973532
Name: 2023-01-01 00:00:00, dtype: float64

`iloc[]` – integer-based access

`iloc[]` is used to access rows and columns based on their position within the DataFrame. This works similarly to a Python list, with 0-based indexing.

In [ ]:
stock_histories.iloc[0]

Apple        151.649142
Nvidia       198.241673
Google       180.780225
SAP          119.962716
Microsoft    249.583068
Tesla        202.973532
Name: 2023-01-01 00:00:00, dtype: float64

Accessing columns and rows + slicing

You can also access columns and rows simultaneously, as well as select only parts of the data (slicing).

In [ ]:
# stock price movements for the first 5 days, only for Apple and Nvidia
stock_histories.loc['2023-01-01':'2023-01-05',['Apple','Nvidia']]

                 Apple      Nvidia
2023-01-01  151.649142  198.241673
2023-01-02  151.381674  199.594771
2023-01-03  153.508826  199.897348
2023-01-04  158.415077  200.626682
2023-01-05  157.832697  197.023032

In [ ]:
# Accessing a specific element:
insurance_df.iloc[2,1]

'Tom Meier'

In [ ]:
stock_histories.loc['2023-12-31', 'Microsoft']

np.float64(484.4990301196811)

Conditional Access

In addition to accessing data via column names or indices, you can also access it using conditions.

In [ ]:
# all contracts starting in May
insurance_df[insurance_df['Policy_Start_Date'].dt.month == 5]

   Police_ID Insured_person  Age  Premium_Amount  Claims Policy_Start_Date
1        102   Anna Schmitz   47           600.0       1        2020-05-20

In [ ]:
# only contracts with high premiums
insurance_df[insurance_df['Premium_Amount'] > 600]

   Police_ID  Insured_person  Age  Premium_Amount  Claims Policy_Start_Date
3        104     Laura Klein   14           620.0       3        2018-11-22
5        106     Julia Weber   31           700.0       1        2020-02-17
7        108  Monika Richter   54           610.0       0        2022-01-01

In [ ]:
# Access is via a Boolean mask
insurance_df['Premium_Amount'] > 600

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7     True
8    False
9    False
Name: Premium_Amount, dtype: bool

In [ ]:
# insurance_df[
#     (insurance_df['Premium_Amount'] > 600) &
#     (insurance_df['Policy_Start_Date'].dt.month == 1)
# ]

# 等價
# insurance_df.query("Premium_Amount > 600 & Policy_Start_Date.dt.month == 1")

Conditional access is very powerful, but it can also very quickly become very complex:

In [ ]:
stock_histories[
    (stock_histories.index.month == 5) & # Filter for the month of May
    ((stock_histories['Nvidia'] > 230) | # Nvidia > 230 or
     (stock_histories['Apple'] > 140)) & # Apple > 155
    (stock_histories['Google'] > 185) & # Google > 185
    (stock_histories['Tesla'] < 260)   # Tesla < 220
]

,Apple,Nvidia,Google,SAP,Microsoft,Tesla
2023-05-10,143.253302,250.312140,238.907208,155.546811,298.995232,255.879194
2023-05-12,139.347720,247.807019,233.701450,155.626138,276.651292,250.853311

Data Enrichment

In data analysis, it is often necessary to expand existing datasets by adding new columns. This can be done, for example, through calculations, importing additional data, or applying functions. Pandas offers a simple way to create new columns and populate them with data.

Typical use cases include:

* Calculating new values ​​based on existing columns (e.g., risk assessments, premium calculations)
* Incorporating external data sources (e.g., inflation rates, exchange rates)
* Creating categories or groupings (e.g., age brackets, loss classes)

New columns can be created in various ways, such as through simple assignment, calculations, or by assigning a series of constant or calculated values.

In the following examples, we will look at how to add new columns to an existing DataFrame.

In [ ]:
# Add contract duration in years
insurance_df['Contract_Duration']=(pd.to_datetime('today')-insurance_df['Policy_Start_Date']).dt.days / 365
insurance_df

,Police_ID,Insured_person,Age,Premium_Amount,Claims,Policy_Start_Date,Contract_Duration
0,101,Max Müller,18,500.0,2,2019-01-15,7.687671
1,102,Anna Schmitz,47,600.0,1,2020-05-20,6.342466
2,103,Tom Meier,49,550.0,0,2021-03-10,5.536986
3,104,Laura Klein,14,620.0,3,2018-11-22,7.835616
4,105,Peter Schneider,15,480.0,2,2019-07-01,7.230137
5,106,Julia Weber,31,700.0,1,2020-02-17,6.597260
6,107,Stefan Jung,1,520.0,1,2021-09-09,5.035616
7,108,Monika Richter,54,610.0,0,2022-01-01,4.723288
8,109,Clara Hofmann,3,580.0,4,2019-12-25,6.745205
9,110,David Krause,16,540.0,2,2020-06-14,6.273973

In [ ]:
# Calculation of absolute performance raltive to the initial value fot Apple stock
stock_history_apple = pd.DataFrame()
stock_history_apple['Price']=stock_histories['Apple']
initial_value_apple = stock_history_apple['Price'].iloc[0] # Initial value of the stock
print(f'Simulated initial value of Apple stock: {initial_value_apple}')
stock_history_apple['AbsPerformance']=stock_history_apple['Price']-initial_value_apple

# Output of the last few rows with the new column
# print(stock_history_apple.tail())
stock_history_apple.tail()

Simulated initial value of Apple stock: 151.64914212169614

                 Price  AbsPerformance
2023-12-27  220.065965       68.416823
2023-12-28  227.143532       75.494390
2023-12-29  226.876749       75.227607
2023-12-30  228.935694       77.286552
2023-12-31  232.349808       80.700666

In addition to simple calculations, there are also standard pandas functions for many use cases.

In [ ]:
# Calculation of daily relative performance
stock_history_apple['RelPerformance'] = stock_history_apple['Price'].pct_change() #Percentage Change
# 這段程式碼的核心是 .pct_change()。它會自動幫你計算「今天的價格相對於昨天價格的百分比變化（報酬率）」。
stock_history_apple.tail()

                 Price  AbsPerformance  RelPerformance
2023-12-27  220.065965       68.416823        0.011452
2023-12-28  227.143532       75.494390        0.032161
2023-12-29  226.876749       75.227607       -0.001175
2023-12-30  228.935694       77.286552        0.009075
2023-12-31  232.349808       80.700666        0.014913

Deleting Data

If you wish to delete a column or row, you can do so as follows:

* Deleting rows: Specific rows can be removed using `drop(index)`. You specify the index of the rows to be deleted.
* Deleting columns: Specific columns can be removed using `drop(column_name, axis=1)`.
In-place option: If you want to apply changes directly to the existing DataFrame, you can use `inplace=True` to avoid creating a copy of the DataFrame.

Note: `drop()` does not allow you to revert to the original data once the rows or columns have been deleted, unless a copy was created beforehand.

In [ ]:
# Delete column
stock_history_apple.drop(['RelPerformance'], axis=1)

                 Price  AbsPerformance
2023-01-01  151.649142        0.000000
2023-01-02  151.381674       -0.267468
2023-01-03  153.508826        1.859684
2023-01-04  158.415077        6.765935
2023-01-05  157.832697        6.183555
...                ...             ...
2023-12-27  220.065965       68.416823
2023-12-28  227.143532       75.494390
2023-12-29  226.876749       75.227607
2023-12-30  228.935694       77.286552
2023-12-31  232.349808       80.700666

[365 rows x 2 columns]

`drop` returns a new DataFrame without the dropped data. Therefore, the original DataFrame remains unchanged unless `inplace=True` is used.

In [ ]:
stock_history_apple

                 Price  AbsPerformance  RelPerformance
2023-01-01  151.649142        0.000000             NaN
2023-01-02  151.381674       -0.267468       -0.001764
2023-01-03  153.508826        1.859684        0.014052
2023-01-04  158.415077        6.765935        0.031961
2023-01-05  157.832697        6.183555       -0.003676
...                ...             ...             ...
2023-12-27  220.065965       68.416823        0.011452
2023-12-28  227.143532       75.494390        0.032161
2023-12-29  226.876749       75.227607       -0.001175
2023-12-30  228.935694       77.286552        0.009075
2023-12-31  232.349808       80.700666        0.014913

[365 rows x 3 columns]

In [ ]:
# Delete lines 3 and 4
stock_history_apple.drop(['2023-01-03','2023-01-04'], inplace=True)
# Note: The index for this dataset is a date
stock_history_apple.head()

                 Price  AbsPerformance  RelPerformance
2023-01-01  151.649142        0.000000             NaN
2023-01-02  151.381674       -0.267468       -0.001764
2023-01-05  157.832697        6.183555       -0.003676
2023-01-06  157.252509        5.603367       -0.003676
2023-01-07  162.460860       10.811717        0.033121

Task: Working with loss data

In this task, you will perform various operations using a sample dataset of loss data. We generate the data using the following code:

In [ ]:
# Create sample data
import numpy as np
import pandas as pd

np.random.seed(42)
data = {
    'Claim_ID': range(1, 16),
    'Policy_Number': [f'PN{str(i).zfill(5)}' for i in np.random.randint(0, 10000, 15)],  # Random policy numbers
    'Claim_Amount': np.random.randint(1000, 5000, size=15),  # Random claim amounts between 1000 and 5000
    'Claim_Date': pd.date_range(start='2023-01-01', periods=15, freq='D'),
    'Policy_Start_Date': pd.date_range(start='2021-01-01', periods=15, freq='D'),
    'Region': [
        'North', 'East', 'South', 'West', 'North',
        'East', 'South', 'West', 'North', 'East',
        'South', 'West', 'North', 'East', 'South'
    ]}

Tasks

1. Create a DataFrame: Create a pandas DataFrame from the data above.

2. Inspect the data: Use the `head()` and `describe()` methods to get an overview of the dataset. What do you notice?

3. Filter the data: Filter for claims with a claim amount greater than 2,000. Which policyholders are affected?

4. Determine contract duration: Add a new column, `Contract Duration`, indicating the duration of the contract in days up to the date of the claim.

5. Calculate average claim amount: Calculate the average claim amount for the claims.

6. Group by claim amount: Group the claim amounts by region.

Note

You can use pandas functions to solve the tasks mentioned above. Please note that we have not yet discussed the approach for task 6. Take a look at the documentation for `mean()` and `groupby()` for this purpose. (['Documentation'](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby))

You can obtain the number of distinct values ​​in the "Region" column using the `value_counts()` function.

In [ ]:
# Create a DataFrame
df = pd.DataFrame(data)
df

    Claim_ID Policy_Number  Claim_Amount Claim_Date Policy_Start_Date Region
0          1       PN07270          1955 2023-01-01        2021-01-01  North
1          2       PN00860          3324 2023-01-02        2021-01-02   East
2          3       PN05390          2184 2023-01-03        2021-01-03  South
3          4       PN05191          1459 2023-01-04        2021-01-04   West
4          5       PN05734          4385 2023-01-05        2021-01-05  North
5          6       PN06265          1021 2023-01-06        2021-01-06   East
6          7       PN00466          3300 2023-01-07        2021-01-07  South
7          8       PN04426          1747 2023-01-08        2021-01-08   West
8          9       PN05578          3904 2023-01-09        2021-01-09  North
9         10       PN08322          4632 2023-01-10        2021-01-10   East
10        11       PN01685          1474 2023-01-11        2021-01-11  South
11        12       PN00769          2082 2023-01-12        2021-01-12   West
12        13       PN06949          3558 2023-01-13        2021-01-13  North
13        14       PN02433          4753 2023-01-14        2021-01-14   East
14        15       PN05311          3047 2023-01-15        2021-01-15  South

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Claim_ID           15 non-null     int64
 1   Policy_Number      15 non-null     object
 2   Claim_Amount       15 non-null     int64
 3   Claim_Date         15 non-null     datetime64[ns]
 4   Policy_Start_Date  15 non-null     datetime64[ns]
 5   Region             15 non-null     object
dtypes: datetime64[ns](2), int64(2), object(2)
memory usage: 852.0+ bytes

In [ ]:
df.describe()

        Claim_ID  Claim_Amount           Claim_Date    Policy_Start_Date
count  15.000000     15.000000                   15                   15
mean    8.000000   2855.000000  2023-01-08 00:00:00  2021-01-08 00:00:00
min     1.000000   1021.000000  2023-01-01 00:00:00  2021-01-01 00:00:00
25%     4.500000   1851.000000  2023-01-04 12:00:00  2021-01-04 12:00:00
50%     8.000000   3047.000000  2023-01-08 00:00:00  2021-01-08 00:00:00
75%    11.500000   3731.000000  2023-01-11 12:00:00  2021-01-11 12:00:00
max    15.000000   4753.000000  2023-01-15 00:00:00  2021-01-15 00:00:00
std     4.472136   1237.955111                  NaN                  NaN

In [ ]:
high_losses = df[df['Claim_Amount']>2000]
print(high_losses)

    Claim_ID Policy_Number  Claim_Amount Claim_Date Policy_Start_Date Region
1          2       PN00860          3324 2023-01-02        2021-01-02   East
2          3       PN05390          2184 2023-01-03        2021-01-03  South
4          5       PN05734          4385 2023-01-05        2021-01-05  North
6          7       PN00466          3300 2023-01-07        2021-01-07  South
8          9       PN05578          3904 2023-01-09        2021-01-09  North
9         10       PN08322          4632 2023-01-10        2021-01-10   East
11        12       PN00769          2082 2023-01-12        2021-01-12   West
12        13       PN06949          3558 2023-01-13        2021-01-13  North
13        14       PN02433          4753 2023-01-14        2021-01-14   East
14        15       PN05311          3047 2023-01-15        2021-01-15  South

In [ ]:
# Calculate contract duration in days up to the date of loss
df['Contract_Duration'] = (df['Claim_Date'] - df['Policy_Start_Date']).dt.days
df.head()

,Claim_ID,Policy_Number,Claim_Amount,Claim_Date,Policy_Start_Date,Region,Contract_Duration
0,1,PN07270,1955,2023-01-01,2021-01-01,North,730
1,2,PN00860,3324,2023-01-02,2021-01-02,East,730
2,3,PN05390,2184,2023-01-03,2021-01-03,South,730
3,4,PN05191,1459,2023-01-04,2021-01-04,West,730
4,5,PN05734,4385,2023-01-05,2021-01-05,North,730

In [ ]:
average_damage_amount = df['Claim_Amount'].mean()
print(f'Average damage amount:{average_damage_amount}')

Average damage amount:2855.0

In [ ]:
# Group claim/damage amounts by region
region_grouped = df.groupby('Region')['Claim_Amount'].agg(['sum', 'mean']).reset_index()
# 在資料分析與程式語言（如 Python Pandas、SQL 等）中，
# 聚合（Aggregation）指的是：將多筆資料壓縮、計算成單一數值的過程。
print("Damage amount by region (Sum and Average):")
print(region_grouped)

Damage amount by region (Sum and Average):
  Region    sum         mean
0   East  13730  3432.500000
1  North  13802  3450.500000
2  South  10005  2501.250000
3   West   5288  1762.666667

# Grouping Data and Aggregation Functions in Pandas

In data analysis, it is often necessary to group data in order to calculate aggregate statistics. Pandas offers powerful functions for grouping data and performing various aggregation operations.

# Fundamental Concepts

* Grouping: Data is grouped using the `groupby()` method. This method splits the data into groups based on the values ​​of one or more columns.
* Aggregation: After grouping, various aggregation functions can be applied to calculate statistical metrics. Commonly used aggregation functions include:

  * `mean()`: Calculates the average.
  * `sum()`: Calculates the sum.
  * `count()`: Counts the number of elements.
  * `max()`: Determines the maximum value.
  * `min()`: Determines the minimum value.

# Example: Aggregating loss data

Suppose we have a DataFrame named `damage_data` containing loss information, with a column for the region and one for the loss amount. We can calculate the average loss per region as follows:

```
# Calculate average damage/claim amount by region
average_damage = damage_data.groupby('Region')['Claim_Amount'].mean()
print(average_damage)
```

# Pivoting with Pandas

Pivoting in Pandas allows you to transform data into a clear, organized table, similar to Excel pivot tables. The `pivot()` function enables you to restructure data based on key columns (such as categories, regions, or time periods). In this process, one column is used for the values ​​you wish to aggregate or display, while other columns serve as the index or column headers.

# Example of pivoting:
Suppose we want to create an overview showing the average claim amount across the various regions.

In [ ]:
# Create a pivot table showing the mean damage amount by region
damage_pivot = df.pivot_table(values='Claim_Amount', index='Region', aggfunc='mean')
damage_pivot

        Claim_Amount
Region
East     3432.500000
North    3450.500000
South    2501.250000
West     1762.666667

#Reading and Writing Data in Pandas DataFrames

Pandas offers powerful functions for reading data from various file formats and writing DataFrames to files. The most common formats are CSV (Comma-Separated Values) and Excel, but JSON, HTML, LaTeX, Parquet, SAS, and others are also supported.

#Reading Data

To read data from a CSV file into a pandas DataFrame, use the read_csv() function. Here is an example:


```
import pandas as pd

# Read a CSV file
df_csv = pd.read_csv('filepath/to_file.csv')

# Output the first five rows of the DataFrame
print(df_csv.head())


# Read an Excel file
df_excel = pd.read_excel('filepath/to_file.xlsx', sheet_name='Sheet1')

# Output the first five rows of the DataFrame
print(df_excel.head())
```

#Writing data

To write a DataFrame to a CSV file, use the to_csv() function. Here is an



```
# Write the DataFrame to a CSV file
df_csv.to_csv('filepath/to_new_file.csv', index=False)

# or

# Write the DataFrame to an Excel file
df_excel.to_excel('filepath/to_new_file.xlsx', sheet_name='Sheet1', index=False)
```

# Handling Missing Data

Missing data is a common issue in real-world datasets. Pandas offers a variety of methods to identify, handle, or clean missing values.

# Detecting Missing Data
You can use the `isnull()` or `isna()` function to detect which entries in a DataFrame are missing. `isnull()` returns `True` if the value is missing (NaN) and `False` if a valid value is present.

Let’s take a look at this using the insurance dataset from earlier.

In [ ]:
# So far the dataset has no missing values, so we create some
nan_df = insurance_df.copy()

# Randomly insert NaN values (approx. 25% of the data)
for col in ['Age', 'Policy_Start_Date', 'Contract_Duration']:
    nan_df.loc[nan_df.sample(frac=0.25).index, col] = np.nan

nan_df

,Police_ID,Insured_person,Age,Premium_Amount,Claims,Policy_Start_Date,Contract_Duration
0,101,Max Müller,18.0,500.0,2,2019-01-15,7.687671
1,102,Anna Schmitz,NaN,600.0,1,2020-05-20,6.342466
2,103,Tom Meier,49.0,550.0,0,NaT,5.536986
3,104,Laura Klein,14.0,620.0,3,2018-11-22,7.835616
4,105,Peter Schneider,15.0,480.0,2,2019-07-01,7.230137
5,106,Julia Weber,31.0,700.0,1,NaT,6.597260
6,107,Stefan Jung,1.0,520.0,1,2021-09-09,5.035616
7,108,Monika Richter,54.0,610.0,0,2022-01-01,NaN
8,109,Clara Hofmann,NaN,580.0,4,2019-12-25,6.745205
9,110,David Krause,16.0,540.0,2,2020-06-14,NaN

In [ ]:
nan_df.isna()

,Police_ID,Insured_person,Age,Premium_Amount,Claims,Policy_Start_Date,Contract_Duration
0,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False
2,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,True
8,False,False,True,False,False,False,False
9,False,False,False,False,False,False,True

In [ ]:
nan_df.isnull().sum()

Police_ID            0
Insured_person       0
Age                  2
Premium_Amount       0
Claims               0
Policy_Start_Date    2
Contract_Duration    2
dtype: int64

# Removing missing data

You can use `dropna()` to remove rows or columns containing missing values. You can control whether all missing values ​​(`how='all'`) or just individual missing values ​​(`how='any'`) are taken into account.

In [ ]:
df_cleaned = nan_df.dropna()
df_cleaned

,Police_ID,Insured_person,Age,Premium_Amount,Claims,Policy_Start_Date,Contract_Duration
0,101,Max Müller,18.0,500.0,2,2019-01-15,7.687671
3,104,Laura Klein,14.0,620.0,3,2018-11-22,7.835616
4,105,Peter Schneider,15.0,480.0,2,2019-07-01,7.230137
6,107,Stefan Jung,1.0,520.0,1,2021-09-09,5.035616

# Filling in missing data

Instead of removing missing values, we can replace them with meaningful values. These could be, for example, the mean, the median, or a specific value. Use the `fillna()` function for this purpose.

In [ ]:
nan_df['Age'].fillna(nan_df['Age'].mean(), inplace = True)
nan_df

/tmp/ipykernel_2027/949611178.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  nan_df['Age'].fillna(nan_df['Age'].mean(), inplace = True)

,Police_ID,Insured_person,Age,Premium_Amount,Claims,Policy_Start_Date,Contract_Duration
0,101,Max Müller,18.00,500.0,2,2019-01-15,7.687671
1,102,Anna Schmitz,24.75,600.0,1,2020-05-20,6.342466
2,103,Tom Meier,49.00,550.0,0,NaT,5.536986
3,104,Laura Klein,14.00,620.0,3,2018-11-22,7.835616
4,105,Peter Schneider,15.00,480.0,2,2019-07-01,7.230137
5,106,Julia Weber,31.00,700.0,1,NaT,6.597260
6,107,Stefan Jung,1.00,520.0,1,2021-09-09,5.035616
7,108,Monika Richter,54.00,610.0,0,2022-01-01,NaN
8,109,Clara Hofmann,24.75,580.0,4,2019-12-25,6.745205
9,110,David Krause,16.00,540.0,2,2020-06-14,NaN

# Task
Now it's your turn. You will find two datasets in the `data` folder:

* car_insurance_claims.csv (car insurance data)
* titanic_train.csv (Titanic passenger data)

Source:

The car insurance data comes from [Databrick](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/4954928053318020/1058911316420443/167703932442645/latest.html). Unfortunately, no further source is cited there.

The Titanic data is taken from Kaggle’s [Titanic-Machine-Learning-Challenge](https://www.kaggle.com/c/titanic/data) and contains data on 892 Titanic passengers. The dataset is used in the challenge to train machine learning algorithms.

# Exercises on the claims dataset
1. Getting an overview
* Task: Load the dataset and get an overview.
  * Use head() to view the first 5 rows of the dataset.
  * Use info() to obtain information about the data types and the number of entries.
  * Display a summary of the numerical columns using describe().

In [ ]:
# from google.colab import files
# files.upload()
damage_df = pd.read_csv('car_insurance_claims.csv')

# damage_df = pd.read_csv('/car_insurance_claims.csv')
damage_df.head()
damage_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), object(21)
memory usage: 312.6+ KB

2. Column access and simple calculations

* Task: Work with individual columns.
  * Show the average value of the `total_claim_amount` column.
  * Find the maximum and minimum values ​​for the `policy_annual_premium` column.
  * Create a new column named `claim_ratio` that calculates the ratio of `policy_annual_premium` to `total_claim_amount`.

In [ ]:
average_claim_amount = damage_df['total_claim_amount'].mean()
# Average total claim amount
print(f'Average total claim amount: {average_damage_amount}')

max_premium = damage_df['policy_annual_premium'].max()
min_premium = damage_df['policy_annual_premium'].min()

# Maximum annual premium
print(f'Maximum annual premium: {max_premium}')
# Minimum annual premium
print(f'Minimum annual premium: {min_premium}')

damage_df['claim_ratio'] = damage_df['policy_annual_premium'] / damage_df['total_claim_amount']

print(damage_df[['total_claim_amount','policy_annual_premium','claim_ratio']].head())

Average total claim amount: 2855.0
Maximum annual premium: 2047.59
Minimum annual premium: 433.33
   total_claim_amount  policy_annual_premium  claim_ratio
0               71610                1406.91     0.019647
1                5070                1197.22     0.236138
2               34650                1413.14     0.040783
3               63400                1415.74     0.022330
4                6500                1583.91     0.243678

3. Filtering Data
* Task: Filter the dataset based on specific conditions.
  * Find all cases where the `incident_type` was reported as "Single Vehicle Collision".
  * Display all incidents that occurred in the state of "NY" (`incident_state`) and where the claim amount (`total_claim_amount`) exceeds 10,000.
  * Find all incidents where more than 2 witnesses were listed.

In [ ]:
single_vehicle_collisions = damage_df[damage_df['incident_type']=='Single Vehicle Collision']
# print(single_vehicle_collisions.head())
ny_high_claims = damage_df[(damage_df['incident_state']=='NY') & (damage_df['total_claim_amount']>10000)]
# print(ny_high_claims.head())
more_than_two_witnesses = damage_df[damage_df['witnesses']>2]
print(more_than_two_witnesses.head())

    months_as_customer  age  policy_number policy_bind_date policy_state  \
2                  134   29         687698       2000-09-06           OH
24                 237   40         736882       1996-02-02           IN
25                   8   35         699044       2013-12-05           OH
26                 257   43         863236       1990-09-20           IN
32                 155   35         336614       2003-08-01           IL

   policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
2     100/300               2000                1413.14         5000000
24    100/300               1000                 883.31               0
25    100/300               2000                1266.92               0
26    100/300               2000                1322.10               0
32   500/1000               1000                1088.34               0

    insured_zip  ... total_claim_amount injury_claim property_claim  \
2        430632  ...              34650         7700           3850
24       434733  ...              77880         7080          14160
25       613982  ...              71500        16500          11000
26       436984  ...               9020         1640            820
32       614780  ...              29790         3310           3310

   vehicle_claim auto_make  auto_model  auto_year fraud_reported _c39  \
2          23100     Dodge         RAM       2007              N  NaN
24         56640      Ford      Escape       2005              N  NaN
25         44000      Ford      Escape       2006              Y  NaN
26          6560    Toyota       Camry       2005              N  NaN
32         23170       BMW    3 Series       2008              N  NaN

   claim_ratio
2     0.040783
24    0.011342
25    0.017719
26    0.146574
32    0.036534

[5 rows x 41 columns]

4. Grouping and Aggregating
* Task: Group data and calculate average values.
  * Group the data by `incident_state` and display the average `total_claim_amount` for each state.
  * Group the data by `insured_occupation` and display the average `injury_claim` amount.
  * Find the average `property_claim` by `auto_make`.

In [ ]:
avg_claim_by_state = damage_df.groupby('incident_state')['total_claim_amount'].mean()
# print(avg_claim_by_state)
avg_injury_claim_by_occupation = damage_df.groupby('insured_occupation')['injury_claim'].mean()
# print(avg_injury_claim_by_occupation)
avg_property_claim_by_auto_make = damage_df.groupby('auto_make')['property_claim'].mean()
print(avg_property_claim_by_auto_make)

auto_make
Accura        7210.588235
Audi          7674.782609
BMW           7889.027778
Chevrolet     6856.973684
Dodge         8122.750000
Ford          7841.250000
Honda         7794.545455
Jeep          7809.701493
Mercedes      7373.692308
Nissan        6920.128205
Saab          7172.250000
Suburu        7393.500000
Toyota        6010.714286
Volkswagen    7634.411765
Name: property_claim, dtype: float64

5. Handling Missing Data
* Task: Handle missing data.
  * Identify which columns contain missing values ​​(`NaN`).
  * Count the missing values ​​in the `authorities_contacted` column.
  * Fill the missing values ​​in the `authorities_contacted` column with the value "Not Contacted".

In [ ]:
missing_values = damage_df.isnull().sum()
print(missing_values)

months_as_customer                0
age                               0
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 0
policy_annual_premium             0
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           0
insured_occupation                0
insured_hobbies                   0
insured_relationship              0
capital-gains                     0
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            91
incident_state                    0
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                0
injury_claim                      0
property_claim                    0
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
claim_ratio                       0
dtype: int64

In [ ]:
missing_authorities_contacted = damage_df['authorities_contacted'].isnull().sum()
print(f"Missing values ​​in 'authorities_contacted':{missing_authorities_contacted}")
# damage_df['authorities_contacted'].fillna('Not Contacted', inplace=True)
damage_df['authorities_contacted'] = damage_df['authorities_contacted'].fillna('Not Contacted')
missing_authorities_contacted = damage_df['authorities_contacted'].isnull().sum()
print(f"Missing values ​​in 'authorities_contacted':{missing_authorities_contacted}")

Missing values ​​in 'authorities_contacted':91
Missing values ​​in 'authorities_contacted':0

6. Time-based analysis
* Task: Work with time data.
  * Convert the `incident_date` column to the datetime format.
  * Determine in which month the highest number of incidents occurred.
  * Display all incidents reported between February 15, 2015, and February 28, 2015.

In [ ]:
# convert column
damage_df['incident_date'] = pd.to_datetime(damage_df['incident_date'])

damage_df['incident_month'] = damage_df['incident_date'].dt.month
# most_incidents_month = damage_df['incident_month'].value_counts().idxmax()
most_incidents_month = damage_df['incident_month'].value_counts().index[0]
print(f"The month with the most incidents is:{most_incidents_month}")

The month with the most incidents is:1

In [ ]:
grouped_by_month = damage_df.groupby('incident_month')['incident_month'].count()
print(grouped_by_month)

# month_counts = damage_df['incident_month'].value_counts()
# # 顯示每個月份的筆數
# print(month_counts)

incident_month
1    516
2    472
3     12
Name: incident_month, dtype: int64

In [ ]:
start_date = '2015-02-15'
end_date = '2015-02-28'
filtered_incidents = damage_df[(damage_df['incident_date'] >= start_date) & (damage_df['incident_date'] <= end_date)]
print(filtered_incidents['incident_date'])

2     2015-02-22
4     2015-02-17
7     2015-02-27
11    2015-02-15
16    2015-02-22
         ...
989   2015-02-15
993   2015-02-17
995   2015-02-22
998   2015-02-26
999   2015-02-26
Name: incident_date, Length: 239, dtype: datetime64[ns]

# Tasks: Analyses of the Titanic dataset
1. Who was the youngest passenger?

Determine the age of the youngest passenger on board the Titanic. Use the 'Age' column for this. What else can you find out about this passenger?

In [ ]:
# from google.colab import files
# files.upload()
titanic_df = pd.read_csv('titanic_train.csv')
titanic_df.info()

Saving titanic_train.csv to titanic_train.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
youngest_passenger = titanic_df[titanic_df['Age']==titanic_df['Age'].min()]
youngest_passenger

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C

2. Survival rate by gender

Examine whether survival on the Titanic was related to the passengers' gender. Calculate the survival rate for men and women separately. Use the *Survived* and *Sex* columns for this purpose.

In [ ]:
# Calculation of survival rate by gender
survival_rate_by_gender = titanic_df.groupby('Sex')['Survived'].mean()

# Output of the survival rate for men and women
print(survival_rate_by_gender)

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

3. Survival chances across the different classes

Does the class in which a passenger traveled influence their chances of survival? Calculate the survival rate for each of the three classes (Pclass) and interpret the result.

In [ ]:
# Calculation of survival rate by passenger class
survival_rate_by_class = titanic_df.groupby('Pclass')['Survived'].mean()
# Output the survival rate for each class
print(survival_rate_by_class)

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

4. Average ticket prices by class

Find out how much passengers paid for their tickets on average in each class. Use the Pclass and Fare columns to calculate the average ticket prices.

In [ ]:
# Calculation of average price by ticket class
price_by_class = titanic_df.groupby('Pclass')['Fare'].mean()

print(price_by_class)

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

5. Largest Families on Board

Find out how many siblings and parents (columns SibSp and Parch) the passengers on board had. Who traveled with the largest family?

In [ ]:
# Calculation of the total number of family members
titanic_df['Family_size'] = titanic_df['SibSp'] + titanic_df['Parch']

# Finding the passenger with the largest family
# largest_family = titanic_df[titanic_df['Family_size'] == titanic_df['Family_size'].max()]
largest_family = titanic_df.loc[titanic_df['Family_size'].idxmax()]

# Output of results
print('Passenger with the largest family:')
print(largest_family[['Name','SibSp','Parch','Family_size']])

# # 1. 找出 Family_size 前兩大的索引（Index），並取出第 2 個 (索引位置 1)
# second_largest_idx = titanic_df['Family_size'].nlargest(2).index[1]

# # 2. 用 .loc 抓出該筆資料
# second_largest_family = titanic_df.loc[second_largest_idx]
# print(second_largest_family)

Passenger with the largest family:
Name           Sage, Master. Thomas Henry
SibSp                                   8
Parch                                   2
Family_size                            10
Name: 159, dtype: object

6. Where did the most passengers board?

Examine at which port the highest number of passengers boarded.

In [ ]:
# Counting passengers at each port
embarked_counts  = titanic_df['Embarked'].value_counts()

# Output of results
print('Passengers by port of embarkation:')
print(embarked_counts)

Passengers by port of embarkation:
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

7. Distribution of age groups

Divide the passengers into different age groups (e.g., children, adolescents, adults, seniors) and examine how these groups affect the survival rate.

In [ ]:
# Definition of age groups
bins = [0, 3, 12, 18, 60, 120] # Age limits for the groups
labels = ['Toddlers', 'Children', 'Adolescents', 'Adults', 'Seniors']  # Labels for the groups

# Creating a new column 'AgeGroup' with the age groups
titanic_df['AgeGroup'] = pd.cut(titanic_df['Age'], bins=bins, labels=labels, right=False)

# Calculating the survival rate for each age group
survival_rate_by_age_group  = titanic_df.groupby('AgeGroup')['Survived'].mean()

# Output of results
# print(f"Survival rate by age group:{survival_rate_by_age_group}")
print("Survival rate by age group:")
print(survival_rate_by_age_group)


# 做法 A：維持現在的行為（推薦）
# 如果你希望所有切分好的年齡層（就算該區間沒人）都顯示出來：
# survival_rate_by_age_group = titanic_df.groupby('AgeGroup', observed=False)['Survived'].mean()

# 做法 B：採用未來的預設行為
# 如果你只想計算與顯示「真的有乘客存在」的年齡層：
# survival_rate_by_age_group = titanic_df.groupby('AgeGroup', observed=True)['Survived'].mean()

Survival rate by age group:
AgeGroup
Toddlers       0.625000
Children       0.545455
Adolescents    0.488889
Adults         0.386087
Seniors        0.269231
Name: Survived, dtype: float64

/tmp/ipykernel_2027/294852699.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survival_rate_by_age_group  = titanic_df.groupby('AgeGroup')['Survived'].mean()

8. Most Valuable Ticket on Board

Find out which was the most expensive ticket (fare) on the Titanic and who purchased it.

In [ ]:
# Find the index of the most expensive ticket
max_fare_index = titanic_df['Fare'].idxmax()

# Retrieve information about the passenger with the most expensive ticket
most_expensive_ticket = titanic_df.loc[max_fare_index]

# Output of results
print('The most expensive ticket was held by the following passenger:')
print(f"Name: {most_expensive_ticket['Name']}")
print(f"Ticket price: {most_expensive_ticket['Fare']}")
print(f"Passenger class: {most_expensive_ticket['Pclass']}")
print(f"Gender: {most_expensive_ticket['Sex']}")
print(f"Age: {most_expensive_ticket['Age']}")

The most expensive ticket was held by the following passenger:
Name: Ward, Miss. Anna
Ticket price: 512.3292
Passenger class: 1
Gender: female
Age: 35.0